---
# tasks file for opt/m10m/roles/flomko.buildbot_worker
# - include: store_passwd.yml

- name: install pip3 packages
  apt:
    name: python3-pip
    update_cache: yes
    state: latest
    cache_valid_time: 86400

- name: install curl packages
  apt:
    name: curl
    update_cache: yes
    state: latest
    cache_valid_time: 86400

- name: Install PIP buildbot worker
  pip:
    executable: pip3
    name: "buildbot-worker"


- name: PAM user
  user:
    name: '{{ buildbot_worker_user }}'
    comment: 'Dedicated user to run the buildbot worker'
    shell: '/bin/bash'

- name: Folder
  file:
    path: '{{ item }}'
    state: directory
    owner: '{{ buildbot_worker_user }}'
    group: '{{ buildbot_worker_user }}'
  with_items:
  - '{{ buildbot_worker_basedir }}'
  - '{{ buildbot_worker_utilities_dir }}'

# - name: Create Utilities
#   copy:
#     src: 'utilities/'
#     dest: '{{ buildbot_worker_utilities_dir }}'
#     owner: '{{ buildbot_worker_user }}'
#     group: '{{ buildbot_worker_user }}'

- name: Create
  command: >
    buildbot-worker create-worker {{ buildbot_worker_basedir }}
    {{ buildbot_worker_master_host }}:{{ buildbot_worker_master_port }}
    {{ buildbot_worker_name }} {{ generated_worker_password }}
  become: yes
  become_method: su
  become_user: '{{ buildbot_worker_user }}'
  args:
    creates: '{{ buildbot_worker_basedir }}/buildbot.tac'

- name: Copy firewall systemd unit file into place (for systemd systems).
  template:
    src: worker.unit.j2
    dest: /etc/systemd/system/buildbot.service
    owner: root
    group: root
    mode: 0644
  when: "ansible_service_mgr == 'systemd'"

- name: "Configure the buildbotservice."
  service:
    name: buildbot
    state: started
    enabled: true


